### ISSUE TITLE
Crash when changing wallpapers when phone is in landscape mode

### ISSUE THREAD

**Issue by 89Q12** [you-apps/WallYou#180]
```
type: logcat
osVersion: google/bluejay/bluejay:14/UQ1A.240105.002/2024011600:user/release-keys
packageName: com.bnyro.wallpaper:24
buffers: main,crash
level: debug

--------- beginning of crash
1707809379.628  6705  9492 E AndroidRuntime: FATAL EXCEPTION: Thread-6
1707809379.628  6705  9492 E AndroidRuntime: Process: com.bnyro.wallpaper, PID: 6705
1707809379.628  6705  9492 E AndroidRuntime: java.lang.IllegalArgumentException: y must be >= 0
1707809379.628  6705  9492 E AndroidRuntime: 	at android.graphics.Bitmap.checkXYSign(Bitmap.java:433)
1707809379.628  6705  9492 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:900)
1707809379.628  6705  9492 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:862)
1707809379.628  6705  9492 E AndroidRuntime: 	at f3.k.run(SourceFile:231)
1707809379.628  6705  9492 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1707832091.843  3731  3870 E AndroidRuntime: FATAL EXCEPTION: Thread-4
1707832091.843  3731  3870 E AndroidRuntime: Process: com.bnyro.wallpaper, PID: 3731
1707832091.843  3731  3870 E AndroidRuntime: java.lang.IllegalArgumentException: y must be >= 0
1707832091.843  3731  3870 E AndroidRuntime: 	at android.graphics.Bitmap.checkXYSign(Bitmap.java:433)
1707832091.843  3731  3870 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:900)
1707832091.843  3731  3870 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:862)
1707832091.843  3731  3870 E AndroidRuntime: 	at f3.k.run(SourceFile:231)
1707832091.843  3731  3870 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
1707843442.643 29635 29781 E AndroidRuntime: FATAL EXCEPTION: Thread-4
1707843442.643 29635 29781 E AndroidRuntime: Process: com.bnyro.wallpaper, PID: 29635
1707843442.643 29635 29781 E AndroidRuntime: java.lang.IllegalArgumentException: y must be >= 0
1707843442.643 29635 29781 E AndroidRuntime: 	at android.graphics.Bitmap.checkXYSign(Bitmap.java:433)
1707843442.643 29635 29781 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:900)
1707843442.643 29635 29781 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:862)
1707843442.643 29635 29781 E AndroidRuntime: 	at f3.k.run(SourceFile:231)
1707843442.643 29635 29781 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```
OS: GrapheneOS, Android 14
APP version: 7.0
Phone: Pixel 6a

App settings:
Combined change
Interval: 15min
Source: Wallhaven

**Comment by blindmodz** [comment]
I get same error with MIUI 14![Screenshot_2024-03-08-14-59-00-543_com.miui.bugreport.jpg](https://github.com/you-apps/WallYou/assets/22939330/c986340f-2550-4c3f-9a76-70e3a10a8219)

**Comment by 89Q12** [comment]
This has been fixed in on the latest releases, closing this.
